site_name: Safire

theme:
  name: material
  extra_css:
    - stylesheets/extra.css
  logo: img/logo.png
  palette:
    - scheme: slate
      primary: blue

nav:
  - Home: index.md
  - Jailbreaking:
    - AttackPipeline: jailbreaking/pipeline.md
    - Attacks:
      - AnagramPuzzleAttack: jailbreaking/attacks/anagram_puzzle_attack.md
      - ConcatAttack: jailbreaking/attacks/concat_attack.md
      - QuestionsPuzzleAttack: jailbreaking/attacks/questions_puzzle_attack.md
      - SystemKeyPolicyIdeasAttack: jailbreaking/attacks/system_key_policy_ideas_attack.md
  - Evaluation:
    - Run Eval: evaluation/run_eval.md
    - Judge: evaluation/judge.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences